### ISSUE TITLE
Integrating sakai lesson tool and SCORM player tool

### ISSUE THREAD

**Issue by aungmyohtet** [frobomjava/sakai-knowledge#3]

**Comment by ThinnThinnAung** [comment]
integrating resources and scorm cloud tool by following the guides. solving build failure

**Comment by waiwai-frobom** [comment]
#waiwai
lessonbuilder project -found lessonpage view and try to add scorm player 
lessonbuilder-tool/src/webapp/templates/ShowPage.html
lessonbuilder-tool/src/resources/messages.properties
lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/beans/SimplePageBean.java
lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/ShowPageProducer.java

#Hninn
file upload and save functions of scorm player projec
sakai\scorm\scorm-tool\src\java\org\sakaiproject\scorm\ui\upload\components\FileUploadForm.java
sakai\scorm\scorm-impl\service\src\java\org\sakaiproject\scorm\service\sakai\impl\SakaiResourceService.java

#thinthin
integrate resources and scorm cloud tool, and build failed
